import streamlit as st
import sys
import os
import base64
from io import BytesIO
from PIL import Image
import importlib

# Add agent directory to path and reload module each run so latest code is used
agent_dir = os.path.join(os.path.dirname(__file__), '..', 'agent')
if agent_dir not in sys.path:
    sys.path.append(agent_dir)
import agent as agent_module  # type: ignore
agent_module = importlib.reload(agent_module)
SimpleAgent = agent_module.SimpleAgent

st.set_page_config(page_title="RAG+MCP Agent", layout="wide")

st.title("🤖 Retrieval-Aware Tool-Using Agent with MCP")
st.markdown("Query the agent and watch it retrieve context and invoke tools")

# Sidebar: endpoint configuration (no hardcoding; defaults from env only)
with st.sidebar:
    st.header("Endpoints")
    plot_default = os.getenv('PLOT_SERVICE_URL', '')
    calc_default = os.getenv('CALCULATOR_URL', '')
    pdf_default = os.getenv('PDF_PARSER_URL', '')
    plot_url = st.text_input("plot-service URL", value=plot_default, placeholder="http://127.0.0.1:8000/mcp/plot")
    calc_url = st.text_input("calculator URL", value=calc_default, placeholder="http://127.0.0.1:8001/mcp/calculate")
    pdf_url = st.text_input("pdf-parser URL", value=pdf_default, placeholder="http://127.0.0.1:8002/mcp/parse")

# Initialize agent with configured endpoints
agent = SimpleAgent({"plot": plot_url, "calculator": calc_url, "pdf": pdf_url})

# Query input
query = st.text_input("Enter your query:", placeholder="e.g., 'Show me a plot of data'")

if st.button("Execute Query") and query:
    with st.spinner("Processing..."):
        try:
            # Execute agent
            result = agent.plan_and_execute(query)
            
            # Display results
            st.success("Query executed successfully!")
            
            # Show plan
            st.subheader("📋 Agent Plan")
            st.info(result['plan'])
            
            # Show tool result if available
            if result['tool_result']:
                st.subheader("🔧 Tool Result")
                tool_result = result['tool_result']
                
                st.json({"status": tool_result.get('status'), "logs": tool_result.get('logs')})
                
                # Display image if present
                if 'result' in tool_result and 'artifact_base64' in tool_result['result']:
                    st.subheader("📊 Generated Plot")
                    img_data = base64.b64decode(tool_result['result']['artifact_base64'])
                    img = Image.open(BytesIO(img_data))
                    st.image(img, caption="Generated by plot-service", use_column_width=True)
            else:
                st.info("No tool was invoked for this query")
                
        except Exception as e:
            st.error(f"Error: {str(e)}")

# Sidebar with info
with st.sidebar:
    st.header("ℹ️ About")
    st.markdown("""
    This demo showcases:
    - **RAG**: Retrieval-Augmented Generation
    - **MCP**: Model Context Protocol tools
    - **Agent**: Autonomous decision-making
    
    The agent:
    1. Retrieves relevant documents
    2. Decides if a tool is needed
    3. Calls MCP endpoints
    4. Returns results
    """)
    
    st.header("🛠️ Available Tools")
    st.markdown("""
    - **plot-service** (port 8000): Generate visualizations
    - **calculator** (port 8001): Evaluate math expressions
    - **pdf-parser** (port 8002): Extract text from PDFs
    """)
